[project]
name = "marketplace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "grpcio-tools>=1.70.0",
    "jinja2>=3.1.6",
    "pytest>=8.3.5",
]
